# Generated by Django 2.2.7 on 2019-11-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intervals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='audio',
            new_name='audio_url',
        ),
    ]
